<?php
require_once '../../conexion.php';
require_once 'fpdf/fpdf.php';
$pdf = new FPDF('P', 'mm', array(85, 200));
$pdf->AddPage();
$pdf->SetMargins(5, 5, 0);
$pdf->SetTitle("Reporte de Salida");
$pdf->SetFont('Arial', 'B', 12);
$id = $_GET['v'];
$id_cliente = $_GET['cl'];
$config = mysqli_query($conexion, "SELECT * FROM datos_empresa");
$datos = mysqli_fetch_assoc($config);
$clientes = mysqli_query($conexion, "SELECT c.*, ct.codigo FROM clientes c LEFT JOIN codigo_telefono ct ON c.id_codigo = ct.id_codigo WHERE id_cliente = $id_cliente");
$datosC = mysqli_fetch_assoc($clientes);
$ventas = mysqli_query($conexion, "SELECT d.*, p.id_producto, p.producto FROM detalle_venta d INNER JOIN productos p ON d.id_producto = p.id_producto WHERE d.id_venta = $id");
$pdf->image("../../assets/img/logo.png", 55, 5, 18, 18, 'PNG');
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 7);
$pdf->Cell(15, 5, utf8_decode("Teléfono: "), 0, 0, 'L');
$pdf->SetFont('Arial', '', 7);
$pdf->Cell(15, 5, $datos['telefono'], 0, 1, 'L');
$pdf->SetFont('Arial', 'B', 7);
$pdf->Cell(15, 5, "Correo: ", 0, 0, 'L');
$pdf->SetFont('Arial', '', 7);
$pdf->Cell(15, 5, utf8_decode($datos['email']), 0, 1, 'L');
$pdf->SetFont('Arial', 'B', 7);
$pdf->Cell(15, 5, utf8_decode("Dirección: "), 0, 0, 'L');
$pdf->SetFont('Arial', '', 7);
$pdf->Cell(15, 5, utf8_decode($datos['direccion']), 0, 1, 'L');
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 9);
$pdf->SetFillColor(0, 150, 200);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(70, 5, "Emisor", 0, 1, 'C', 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(30, 5, utf8_decode('Nombre'), 0, 0, 'L');
$pdf->Cell(20, 5, utf8_decode('Cédula'), 0, 0, 'L');
$pdf->Cell(20, 5, utf8_decode('Teléfono'), 0, 1, 'L');
$pdf->SetFont('Arial', '', 7);
$pdf->Cell(30, 5, utf8_decode($datosC['nombre_cliente']), 0, 0, 'L');
$pdf->Cell(20, 5, utf8_decode($datosC['cedula_cliente']), 0, 0, 'L');
$pdf->Cell(20, 5, utf8_decode($datosC['codigo'] . $datosC['nro_telefono']), 0, 1, 'L');
$pdf->Ln(3);
$pdf->SetFont('Arial', 'B', 9);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(70, 5, "Detalle de Producto", 2, 1, 'C', 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(30, 5, utf8_decode('Descripción'), 0, 0, 'L');
$pdf->Cell(10, 5, 'Cant.', 0, 0, 'L');
$pdf->Cell(15, 5, 'Precio', 0, 0, 'L');
$pdf->Cell(15, 5, 'Sub Total.', 0, 1, 'L');
$pdf->SetFont('Arial', '', 7);
$total = 0.00;
$desc = 0.00;
while ($row = mysqli_fetch_assoc($ventas)) {
    $pdf->Cell(30, 5, $row['producto'], 0, 0, 'L');
    $pdf->Cell(10, 5, $row['cantidad'], 0, 0, 'L');
    $pdf->Cell(15, 5, $row['precio'], 0, 0, 'L');
    $sub_total = $row['total'];
    $total = $total + $sub_total;
    $desc = $desc + $row['descuento'];
    $pdf->Cell(15, 5, number_format($sub_total, 2, '.', ','), 0, 1, 'L');
}
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(65, 5, 'Descuento Total', 0, 1, 'R');
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(65, 5, number_format($desc, 2, '.', ','), 0, 1, 'R');
$pdf->SetFont('Arial', 'B', 9);
$pdf->Cell(65, 5, 'Total a Pagar', 0, 1, 'R');
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(65, 5, number_format($total, 2, '.', ','), 0, 1, 'R');

$pdf->Output("Reporte.pdf", "I");

?>